image: gitpod/workspace-full

tasks:
  - name: Install & Start
    init: |
      docker-compose build
    command: |
      docker-compose up
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: open-preview
